services:
  - type: web
    name: saferoute-api
    env: python
    region: singapore
    plan: free
    buildCommand: "cd backend && pip install -r requirements.txt"
    startCommand: "cd backend && alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: ENABLE_PG
        value: "true"
      - key: READ_FROM_PG
        value: "true"
      - key: DATABASE_URL
        value: postgresql+asyncpg://postgres.hcsmypvaolyphuacgfbs:Anshuman%40SafeRoute@aws-1-ap-northeast-1.pooler.supabase.com:6543/postgres
      - key: DOC_NUMBER_SALT
        sync: false
      - key: TUID_SALT
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: PRIVATE_KEY_BASE64
        sync: false # Set this in the Render dashboard
      - key: PUBLIC_KEY_BASE64
        sync: false # Set this in the Render dashboard
      - key: ENVIRONMENT
        value: "production"
      - key: ALLOWED_ORIGINS
        value: "*" # Change this to your Vercel URL later for better security
      - key: PYTHON_VERSION
        value: "3.10.0"
