# app/services/qr_service.py
"""
SafeRoute QR Service — RS256 JWT Signing for Digital Identity QR Codes.
Separate from auth JWTs: typ=SR-QR, sub=tuid, exp=365 days.
Uses existing private_key.pem / public_key.pem generated by generate_keys.py.
"""
import datetime
from typing import Optional, Dict, Any
import jwt
from app.config import settings
from app.logging_config import logger


class QRService:
    """Signs and verifies RS256 QR JWTs for tourist identity verification."""

    def __init__(self):
        self._private_key: Optional[str] = None
        self._public_key: Optional[str] = None
        self._algorithm = "RS256"
        self._load_keys()

    def _load_keys(self) -> None:
        """Load RSA keys from paths configured in settings. Fails loudly in production."""
        try:
            with open(settings.PRIVATE_KEY_PATH, "r") as f:
                self._private_key = f.read()
            with open(settings.PUBLIC_KEY_PATH, "r") as f:
                self._public_key = f.read()
            logger.info("✅ QRService: RS256 keys loaded successfully.")
        except FileNotFoundError as e:
            logger.warning(f"⚠️  QRService: RSA keys not found ({e}). QR JWT signing disabled.")
            self._private_key = None
            self._public_key = None

    @property
    def is_available(self) -> bool:
        """Returns True if keys are loaded and signing is possible."""
        return self._private_key is not None and self._public_key is not None

    def sign_qr_jwt(self, tuid: str, full_name: str, nationality: str) -> str:
        """
        Sign a QR identity JWT with RS256.

        Payload:
          iss  — "saferoute-v3"
          sub  — tuid (e.g. SR-IN-26-A3F7C291B4E8)
          name — tourist full name (visible on QR scan, acceptable PII)
          nat  — ISO 3166-1 alpha-2 nationality
          ver  — "3" (protocol version)
          typ  — "SR-QR" (distinguishes from auth tokens)
          iat  — issued at (UTC epoch)
          exp  — issued at + QR_JWT_EXPIRY_DAYS (default 365 days)

        Raises:
            RuntimeError: if RSA keys are not loaded.
        """
        if not self.is_available:
            raise RuntimeError(
                "QRService: RSA private key not loaded. "
                "Run generate_keys.py and set PRIVATE_KEY_PATH in .env"
            )

        now = datetime.datetime.utcnow()
        expiry = now + datetime.timedelta(days=settings.QR_JWT_EXPIRY_DAYS)

        payload = {
            "iss": "saferoute-v3",
            "sub": tuid,
            "name": full_name,
            "nat": nationality.upper(),
            "ver": "3",
            "typ": "SR-QR",
            "iat": int(now.timestamp()),
            "exp": int(expiry.timestamp()),
        }

        token = jwt.encode(payload, self._private_key, algorithm=self._algorithm)
        return token

    def verify_qr_jwt(self, token: str) -> Optional[Dict[str, Any]]:
        """
        Verify a QR JWT using the public key.
        Used by the authority scan endpoint to validate QR content offline.

        Returns:
            Decoded payload dict if valid, None if invalid/expired.
        """
        if not self._public_key:
            logger.warning("QRService: Cannot verify — public key not loaded.")
            return None
        try:
            payload = jwt.decode(
                token,
                self._public_key,
                algorithms=[self._algorithm],
                options={"verify_typ": False},  # typ is custom "SR-QR"
            )
            # Reject auth tokens used as QR tokens
            if payload.get("ver") != "3":
                return None
            return payload
        except (jwt.ExpiredSignatureError, jwt.InvalidTokenError) as e:
            logger.warning(f"QRService: JWT verification failed: {e}")
            return None

    def get_public_key_pem(self) -> Optional[str]:
        """Return the PEM public key for /.well-known/qr-public-key endpoint."""
        return self._public_key


# Module-level singleton — import and use directly
qr_service = QRService()
