"""add_trips_and_trip_stops_tables

Revision ID: 8f6aab2fc336
Revises: a1b2c3d4e5f6
Create Date: 2026-05-04 01:53:33.944322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f6aab2fc336'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authorities',
    sa.Column('authority_id', sa.String(length=30), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('designation', sa.String(length=100), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('badge_id', sa.String(length=50), nullable=False),
    sa.Column('jurisdiction_zone', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('failed_login_attempts', sa.BigInteger(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('authority_id')
    )
    with op.batch_alter_table('authorities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_authorities_badge_id'), ['badge_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_authorities_email'), ['email'], unique=True)

    op.create_table('destinations',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('district', sa.String(length=100), nullable=False),
    sa.Column('altitude_m', sa.BigInteger(), nullable=True),
    sa.Column('center_lat', sa.Float(), nullable=False),
    sa.Column('center_lng', sa.Float(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('difficulty', sa.String(length=20), nullable=True),
    sa.Column('connectivity', sa.String(length=20), nullable=True),
    sa.Column('best_season', sa.String(length=100), nullable=True),
    sa.Column('warnings_json', sa.Text(), nullable=True),
    sa.Column('authority_id', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('destinations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_destinations_authority_id'), ['authority_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_destinations_state'), ['state'], unique=False)

    op.create_table('tourists',
    sa.Column('tourist_id', sa.String(length=30), nullable=False),
    sa.Column('tuid', sa.String(length=24), nullable=True),
    sa.Column('document_number_hash', sa.Text(), nullable=True),
    sa.Column('date_of_birth', sa.String(length=10), nullable=False),
    sa.Column('nationality', sa.String(length=2), nullable=False),
    sa.Column('migrated_from_legacy', sa.Boolean(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('document_type', sa.String(length=20), nullable=False),
    sa.Column('photo_url', sa.Text(), nullable=True),
    sa.Column('photo_object_key', sa.Text(), nullable=True),
    sa.Column('document_object_key', sa.Text(), nullable=True),
    sa.Column('photo_base64_legacy', sa.Text(), nullable=True),
    sa.Column('emergency_contact_name', sa.String(length=255), nullable=True),
    sa.Column('emergency_contact_phone', sa.String(length=30), nullable=True),
    sa.Column('trip_start_date', sa.DateTime(), nullable=True),
    sa.Column('trip_end_date', sa.DateTime(), nullable=True),
    sa.Column('destination_state', sa.String(length=100), nullable=True),
    sa.Column('qr_data', sa.Text(), nullable=True),
    sa.Column('connectivity_level', sa.String(length=20), nullable=False),
    sa.Column('offline_mode_required', sa.Boolean(), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('blood_group', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('tourist_id')
    )
    with op.batch_alter_table('tourists', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tourists_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_tourists_destination_state'), ['destination_state'], unique=False)
        batch_op.create_index(batch_op.f('ix_tourists_document_number_hash'), ['document_number_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_tourists_tuid'), ['tuid'], unique=True)

    op.create_table('zones',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('destination_id', sa.String(length=50), nullable=False),
    sa.Column('authority_id', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('shape', sa.String(length=20), nullable=False),
    sa.Column('center_lat', sa.Float(), nullable=True),
    sa.Column('center_lng', sa.Float(), nullable=True),
    sa.Column('radius_m', sa.Float(), nullable=True),
    sa.Column('polygon_json', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('zones', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_zones_authority_id'), ['authority_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_zones_destination_id'), ['destination_id'], unique=False)

    op.create_table('authority_scan_log',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('authority_id', sa.String(length=30), nullable=False),
    sa.Column('scanned_tuid', sa.String(length=24), nullable=False),
    sa.Column('tourist_id', sa.String(length=30), nullable=True),
    sa.Column('scanned_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('photo_url_generated', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['authority_id'], ['authorities.authority_id'], ),
    sa.ForeignKeyConstraint(['tourist_id'], ['tourists.tourist_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('authority_scan_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_authority_scan_log_authority_id'), ['authority_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_authority_scan_log_scanned_at'), ['scanned_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_authority_scan_log_scanned_tuid'), ['scanned_tuid'], unique=False)

    op.create_table('emergency_contacts',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('destination_id', sa.String(length=50), nullable=True),
    sa.Column('tourist_id', sa.String(length=30), nullable=True),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=False),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['tourist_id'], ['tourists.tourist_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('emergency_contacts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_emergency_contacts_destination_id'), ['destination_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_emergency_contacts_tourist_id'), ['tourist_id'], unique=False)

    op.create_table('location_pings',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tourist_id', sa.String(length=30), nullable=False),
    sa.Column('tuid', sa.String(length=24), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('speed_kmh', sa.Float(), nullable=True),
    sa.Column('accuracy_meters', sa.Float(), nullable=True),
    sa.Column('zone_status', sa.String(length=20), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tourist_id'], ['tourists.tourist_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('location_pings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_location_pings_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_location_pings_tourist_id'), ['tourist_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_location_pings_tuid'), ['tuid'], unique=False)

    op.create_table('sos_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tourist_id', sa.String(length=30), nullable=False),
    sa.Column('tuid', sa.String(length=24), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('trigger_type', sa.String(length=30), nullable=False),
    sa.Column('dispatch_status', sa.String(length=30), nullable=False),
    sa.Column('correlation_id', sa.String(length=50), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('is_synced', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['tourist_id'], ['tourists.tourist_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sos_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sos_events_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_sos_events_tourist_id'), ['tourist_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sos_events_tuid'), ['tuid'], unique=False)

    op.create_table('tourist_destinations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tourist_id', sa.String(length=30), nullable=False),
    sa.Column('destination_id', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('visit_date_from', sa.DateTime(), nullable=False),
    sa.Column('visit_date_to', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tourist_id'], ['tourists.tourist_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tourist_destinations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tourist_destinations_tourist_id'), ['tourist_id'], unique=False)

    op.create_table('trips',
    sa.Column('trip_id', sa.String(length=40), nullable=False),
    sa.Column('tourist_id', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('trip_start_date', sa.DateTime(), nullable=False),
    sa.Column('trip_end_date', sa.DateTime(), nullable=False),
    sa.Column('primary_state', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['tourist_id'], ['tourists.tourist_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('trip_id')
    )
    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trips_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_trips_tourist_id'), ['tourist_id'], unique=False)

    op.create_table('trip_stops',
    sa.Column('stop_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trip_id', sa.String(length=40), nullable=False),
    sa.Column('destination_id', sa.String(length=30), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('destination_state', sa.String(length=100), nullable=True),
    sa.Column('visit_date_from', sa.DateTime(), nullable=False),
    sa.Column('visit_date_to', sa.DateTime(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('center_lat', sa.Float(), nullable=True),
    sa.Column('center_lng', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.trip_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('stop_id')
    )
    with op.batch_alter_table('trip_stops', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trip_stops_trip_id'), ['trip_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip_stops', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trip_stops_trip_id'))

    op.drop_table('trip_stops')
    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trips_tourist_id'))
        batch_op.drop_index(batch_op.f('ix_trips_status'))

    op.drop_table('trips')
    with op.batch_alter_table('tourist_destinations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tourist_destinations_tourist_id'))

    op.drop_table('tourist_destinations')
    with op.batch_alter_table('sos_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sos_events_tuid'))
        batch_op.drop_index(batch_op.f('ix_sos_events_tourist_id'))
        batch_op.drop_index(batch_op.f('ix_sos_events_timestamp'))

    op.drop_table('sos_events')
    with op.batch_alter_table('location_pings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_location_pings_tuid'))
        batch_op.drop_index(batch_op.f('ix_location_pings_tourist_id'))
        batch_op.drop_index(batch_op.f('ix_location_pings_timestamp'))

    op.drop_table('location_pings')
    with op.batch_alter_table('emergency_contacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_emergency_contacts_tourist_id'))
        batch_op.drop_index(batch_op.f('ix_emergency_contacts_destination_id'))

    op.drop_table('emergency_contacts')
    with op.batch_alter_table('authority_scan_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_authority_scan_log_scanned_tuid'))
        batch_op.drop_index(batch_op.f('ix_authority_scan_log_scanned_at'))
        batch_op.drop_index(batch_op.f('ix_authority_scan_log_authority_id'))

    op.drop_table('authority_scan_log')
    with op.batch_alter_table('zones', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_zones_destination_id'))
        batch_op.drop_index(batch_op.f('ix_zones_authority_id'))

    op.drop_table('zones')
    with op.batch_alter_table('tourists', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tourists_tuid'))
        batch_op.drop_index(batch_op.f('ix_tourists_document_number_hash'))
        batch_op.drop_index(batch_op.f('ix_tourists_destination_state'))
        batch_op.drop_index(batch_op.f('ix_tourists_created_at'))

    op.drop_table('tourists')
    with op.batch_alter_table('destinations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_destinations_state'))
        batch_op.drop_index(batch_op.f('ix_destinations_authority_id'))

    op.drop_table('destinations')
    with op.batch_alter_table('authorities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_authorities_email'))
        batch_op.drop_index(batch_op.f('ix_authorities_badge_id'))

    op.drop_table('authorities')
    # ### end Alembic commands ###
