"""initial_migration_batch

Revision ID: cb7bc0b62d51
Revises:
Create Date: 2026-05-01 03:42:30.463830

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb7bc0b62d51'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _table_exists(table):
    bind = op.get_bind()
    insp = sa.inspect(bind)
    return insp.has_table(table)

def _column_exists(table, column):
    if not _table_exists(table):
        return False
    bind = op.get_bind()
    insp = sa.inspect(bind)
    columns = insp.get_columns(table)
    return any(c['name'] == column for c in columns)

def _index_exists(table, index):
    if not _table_exists(table):
        return False
    bind = op.get_bind()
    insp = sa.inspect(bind)
    indexes = insp.get_indexes(table)
    return any(i['name'] == index for i in indexes)

def _fk_exists(table, fk_name):
    if not _table_exists(table):
        return False
    bind = op.get_bind()
    insp = sa.inspect(bind)
    fks = insp.get_foreign_keys(table)
    return any(fk['name'] == fk_name for fk in fks)

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('authorities', schema=None) as batch_op:
        batch_op.alter_column('authority_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=30),
               nullable=False)
        if not _index_exists('authorities', 'ix_authorities_badge_id'):
            batch_op.create_index(batch_op.f('ix_authorities_badge_id'), ['badge_id'], unique=True)
        if not _index_exists('authorities', 'ix_authorities_email'):
            batch_op.create_index(batch_op.f('ix_authorities_email'), ['email'], unique=True)

    with op.batch_alter_table('sos_events', schema=None) as batch_op:
        if not _column_exists('sos_events', 'dispatch_status'):
            batch_op.add_column(sa.Column('dispatch_status', sa.String(length=30), nullable=True))
        if not _column_exists('sos_events', 'correlation_id'):
            batch_op.add_column(sa.Column('correlation_id', sa.String(length=50), nullable=True))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('tourist_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=30),
               nullable=False)
        batch_op.alter_column('latitude',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               nullable=False)
        batch_op.alter_column('longitude',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               nullable=False)
        batch_op.alter_column('trigger_type',
               existing_type=sa.TEXT(),
               type_=sa.String(length=30),
               nullable=False)
        batch_op.alter_column('timestamp',
               existing_type=sa.TEXT(),
               type_=sa.DateTime(),
               nullable=False)
        batch_op.alter_column('is_synced',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               nullable=False,
               existing_server_default=sa.text('0'))
        if not _index_exists('sos_events', 'ix_sos_events_timestamp'):
            batch_op.create_index(batch_op.f('ix_sos_events_timestamp'), ['timestamp'], unique=False)
        if not _index_exists('sos_events', 'ix_sos_events_tourist_id'):
            batch_op.create_index(batch_op.f('ix_sos_events_tourist_id'), ['tourist_id'], unique=False)
        if not _fk_exists('sos_events', 'fk_sos_events_tourist_id'):
            batch_op.create_foreign_key('fk_sos_events_tourist_id', 'tourists', ['tourist_id'], ['tourist_id'])

    with op.batch_alter_table('tourists', schema=None) as batch_op:
        # NOTE: All new columns added to an existing table MUST be nullable=True
        # or have a server_default, because Postgres refuses to add a NOT NULL
        # column when rows already exist (they would have NULL for the new column).
        # NOT NULL is enforced at the ORM/application layer instead.
        for col_name, col_type in [
            ('full_name', sa.String(length=255)),
            ('document_type', sa.String(length=20)),
            ('document_number', sa.String(length=50)),  # deprecated, use document_number_hash
            ('photo_url', sa.Text()),
            ('photo_base64_legacy', sa.Text()),
            ('emergency_contact_name', sa.String(length=255)),
            ('emergency_contact_phone', sa.String(length=30)),
            ('trip_start_date', sa.DateTime()),
            ('trip_end_date', sa.DateTime()),
            ('destination_state', sa.String(length=100)),
            ('qr_data', sa.String(length=255)),
            ('connectivity_level', sa.String(length=20)),
            ('risk_level', sa.String(length=20)),
            ('blood_group', sa.String(length=10)),
        ]:
            if not _column_exists('tourists', col_name):
                batch_op.add_column(sa.Column(col_name, col_type, nullable=True))

        # Boolean columns need a server_default so existing rows get False
        if not _column_exists('tourists', 'offline_mode_required'):
            batch_op.add_column(sa.Column('offline_mode_required', sa.Boolean(), server_default=sa.text('false'), nullable=False))

        if not _column_exists('tourists', 'created_at'):
            batch_op.add_column(sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
        if not _column_exists('tourists', 'updated_at'):
            batch_op.add_column(sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))

        batch_op.alter_column('tourist_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=30),
               nullable=False)

        if not _index_exists('tourists', 'ix_tourists_created_at'):
            batch_op.create_index(batch_op.f('ix_tourists_created_at'), ['created_at'], unique=False)
        if not _index_exists('tourists', 'ix_tourists_destination_state'):
            batch_op.create_index(batch_op.f('ix_tourists_destination_state'), ['destination_state'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tourists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data', sa.TEXT(), nullable=False))
        batch_op.drop_index(batch_op.f('ix_tourists_destination_state'))
        batch_op.drop_index(batch_op.f('ix_tourists_created_at'))
        batch_op.alter_column('tourist_id',
               existing_type=sa.String(length=30),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('blood_group')
        batch_op.drop_column('risk_level')
        batch_op.drop_column('offline_mode_required')
        batch_op.drop_column('connectivity_level')
        batch_op.drop_column('qr_data')
        batch_op.drop_column('destination_state')
        batch_op.drop_column('trip_end_date')
        batch_op.drop_column('trip_start_date')
        batch_op.drop_column('emergency_contact_phone')
        batch_op.drop_column('emergency_contact_name')
        batch_op.drop_column('photo_base64_legacy')
        batch_op.drop_column('photo_url')
        batch_op.drop_column('document_number')
        batch_op.drop_column('document_type')
        batch_op.drop_column('full_name')

    with op.batch_alter_table('sos_events', schema=None) as batch_op:
        batch_op.drop_constraint('fk_sos_events_tourist_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_sos_events_tourist_id'))
        batch_op.drop_index(batch_op.f('ix_sos_events_timestamp'))
        batch_op.alter_column('is_synced',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('timestamp',
               existing_type=sa.DateTime(),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('trigger_type',
               existing_type=sa.String(length=30),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('longitude',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               nullable=True)
        batch_op.alter_column('latitude',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               nullable=True)
        batch_op.alter_column('tourist_id',
               existing_type=sa.String(length=30),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
        batch_op.drop_column('correlation_id')
        batch_op.drop_column('dispatch_status')

    with op.batch_alter_table('authorities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data', sa.TEXT(), nullable=False))
        batch_op.drop_index(batch_op.f('ix_authorities_email'))
        batch_op.drop_index(batch_op.f('ix_authorities_badge_id'))
        batch_op.alter_column('authority_id',
               existing_type=sa.String(length=30),
               type_=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###
